name: ccache-brlin # upstream preferred name request in progress
title: ccache (UNOFFICIAL)
summary: A fast C/C++ compiler cache
description: |
  ccache is a compiler cache. It [speeds up recompilation](https://ccache.samba.org/performance.html)
  by caching previous compilations and detecting when the same
  compilation is being done again. Supported languages are C, C++,
  Objective-C and Objective-C++.

  ## Features ##
  - Keeps statistics on hits/misses.
  - Automatic cache size management.
  - Can cache compilations that generate warnings.
  - Easy installation.
  - Low overhead.
  - Optionally uses hard links where possible to avoid copies.

  ## NOTE ##
  This is not an official distribution of ccache, refer the [issue tracker](https://github.com/Lin-Buo-Ren/ccache-snap/issues)
  regarding to any issues regarding the use of this snap.

base: core18
adopt-info: ccache
grade: devel
confinement: devmode

parts:
  ccache:
    plugin: nil

apps:
  ccache:
    adapter: full
    command: bin/ccache
    command-chain:
    - bin/ccache-launch
