name: ccache
title: ccache (UNOFFICIAL)
summary: A fast C/C++ compiler cache
description: |
  ccache is a compiler cache. It [speeds up recompilation][1]
  by caching previous compilations and detecting when the same
  compilation is being done again. Supported languages are C, C++,
  Objective-C and Objective-C++.

  **Features**

  - Keeps statistics on hits/misses.
  - Automatic cache size management.
  - Can cache compilations that generate warnings.
  - Easy installation.
  - Low overhead.
  - Optionally uses hard links where possible to avoid copies.

  **NOTE**

  This is not an official distribution of ccache, refer the [issue tracker][2]
  regarding to any issues regarding the use of this snap.

  [1]: https://ccache.samba.org/performance.html
  [2]: https://github.com/Lin-Buo-Ren/ccache-snap/issues

license: GPL-3.0+

adopt-info: ccache
base: core18
confinement: classic
grade: stable

parts:
  ccache:
    after:
    - selective-checkout

    source: https://github.com/ccache/ccache.git
    source-depth: 100
    override-pull: |
      snapcraftctl pull
      "$SNAPCRAFT_STAGE"/scriptlets/selective-checkout \
        --append-packaging-revision

    plugin: autotools
    build-packages:
    # For building documentation
    - asciidoc
    - xsltproc

    - gperf
    - zlib1g-dev

  launchers:
    source: snap/local/launchers

    plugin: dump
    organize:
      '*': bin/

  selective-checkout:
    plugin: nil
    build-packages:
    - git
    stage-snaps:
    - selective-checkout

apps:
  ccache:
    adapter: full
    command: bin/ccache
    command-chain:
    - bin/ccache-launch

#plugs:
  #home:
  #removable-media: # Non-autoconnect
